apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: mosgor/backend
          ports:
            - containerPort: 8082
          env:
            - name: POSTGRES_HOST
              value: postgres
            - name: REDIS_HOST
              value: redis