version: '3.9'

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adm
      POSTGRES_DB: Coursework
    # ports:
    #   - '5438:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./db_scripts/postgresql:/docker-entrypoint-initdb.d

  redis:
    image: redis:latest
    restart: always
    # ports:
    #   - '6379:6379'

  backend:
    build: ./backend
    restart: always
    ports:
      - '8082:8082'
    depends_on:
      - postgres
      - redis

  frontend:
    build: ./frontend
    restart: always
    # ports:
    #   - '80:80'
    environment:
      - REACT_APP_API_URL=http://backend:8082
    depends_on:
      - backend
 
  nginx:
    image: nginx:latest
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
