apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    user nginx;
    worker_processes    auto;
    events { worker_connections 1024; }
    http {
      server {
        listen 80;
        location / {
            proxy_pass http://frontend:80;
        }
      }	
    }