CREATE TABLE products (
	id SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	description VARCHAR(255) NOT NULL,
	image_url VARCHAR(255) NOT NULL,
	price DECIMAL NOT NULL,
	weight DECIMAL DEFAULT 1
);