apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
data:
  init.sql: |
    CREATE TABLE products (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    image_url VARCHAR(255) NOT NULL,
    price DECIMAL NOT NULL,
    weight DECIMAL DEFAULT 1
    );
    INSERT INTO products (name, description, image_url, price, weight)
    VALUES ('Сыр "Чёрный граф"', 'Сыр белорусского производства с ароматом топлёного молока', 'https://milknet.ru/data/tradeboard/38470/tradeboardVm57xf_img.webp', 350, 0.5);
    INSERT INTO products (name, description, image_url, price, weight)
    VALUES ('Яблоки "Медовый хруст"', 'Сладкий сорт яблок с медовым привкусом', 'https://www.auchan.ru/f/c/insecure/w:520/plain/https://www.auchan.ru/files/original/5599615', 250, 0.6);